version: '3'

services:
  webgis-auth-staging:
    image: paschendale/scope-auth
    hostname: webgis-auth
    environment:
      - DATABASE_URL=
      - AUTH_MASTER_EMAIL=
      - AUTH_MASTER_PASSWORD=
      - AUTH_SECRET=
    ports:
      - 111:3000
    labels:
      - "com.centurylinklabs.watchtower.scope=webgis.itabirito.staging"


  webgis-proxy-staging:
    image: nginx
    volumes:
      - './proxy/proxy.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - 110:80

  webgis-frontend-staging:
    image: paschendale/webgis-itabirito-frontend:latest
    container_name: webgis-frontend-staging
    hostname: webgis-frontend
    labels:
      - "com.centurylinklabs.watchtower.scope=webgis.itabirito.staging"

  webgis-backend-staging:
    image: paschendale/webgis-itabirito-backend:latest
    container_name: webgis-backend-staging
    hostname: webgis-backend
    environment:
      - PG_DATABASE=
      - PG_USER=
      - PG_HOST=
      - PG_PASSWORD=
      - PG_PORT=
      - QGIS_SERVER_URL=https://qgis.itabirito.genteufv.com.br/
      - AUTH_SERVER_URL=https://staging.auth.itabirito.genteufv.com.br/
    labels:
      - "com.centurylinklabs.watchtower.scope=webgis.itabirito.staging"

  webgis-watchtower-staging:
    image: containrrr/watchtower
    container_name: webgis-watchtower-staging
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 webgis-frontend-staging webgis-backend-staging webgis-auth --scope webgis.itabirito.staging
    labels:
      - "com.centurylinklabs.watchtower.scope=webgis.itabirito.staging"
