version: '3'

services:
  webgis-auth:
    image: paschendale/scope-auth
    hostname: webgis-auth
    environment:
      - DATABASE_URL=
      - AUTH_MASTER_EMAIL=
      - AUTH_MASTER_PASSWORD=
      - AUTH_SECRET=
    ports:
      - 101:3000
    labels:
      - "com.centurylinklabs.watchtower.scope=webgis.itabirito.staging"


  webgis-frontend:
    image: paschendale/webgis-itabirito-frontend:stable
    container_name: webgis-frontend
    hostname: webgis-frontend
    labels:
      - "com.centurylinklabs.watchtower.scope=webgis.itabirito"

  webgis-backend:
    image: paschendale/webgis-itabirito-backend:stable
    container_name: webgis-backend
    hostname: webgis-backend
    environment:
      - PG_DATABASE=
      - PG_USER=
      - PG_HOST=
      - PG_PASSWORD=
      - PG_PORT=
      - QGIS_SERVER_URL=https://qgis.itabirito.genteufv.com.br/
      - AUTH_SERVER_URL=https://auth.itabirito.genteufv.com.br/
    labels:
      - "com.centurylinklabs.watchtower.scope=webgis.itabirito"

  webgis-watchtower:
    image: containrrr/watchtower
    container_name: webgis-watchtower
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 webgis-frontend webgis-backend webgis-auth --scope webgis.itabirito
    labels:
      - "com.centurylinklabs.watchtower.scope=webgis.itabirito"
