FROM node:16 AS builder

WORKDIR /app

COPY ./app .

RUN yarn
RUN yarn build

FROM nginx:latest

WORKDIR /app/build

COPY --from=builder /app/build .
COPY --from=builder /app/nginx.conf /etc/nginx/conf.d/default.conf

CMD nginx -g 'daemon off;'
