version: '3'

services:
  webgis-proxy:
    image: nginx
    volumes:
      - './proxy/proxy.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - 110:80

  webgis-frontend:
    image: paschendale/webgis-itabirito-frontend:latest
    container_name: webgis-frontend
    hostname: webgis-frontend
    labels:
      - "com.centurylinklabs.watchtower.scope=webgis.itabirito.staging"

  webgis-backend:
    image: paschendale/webgis-itabirito-backend:latest
    container_name: webgis-backend
    hostname: webgis-backend
    environment:
      - PG_DATABASE=itabirito
      - PG_USER=marotta
      - PG_HOST=200.235.135.49
      - PG_PASSWORD=o9*h@,
      - PG_PORT=5432
      - QGIS_SERVER_URL=https://qgis.itabirito.genteufv.com.br/
    labels:
      - "com.centurylinklabs.watchtower.scope=webgis.itabirito.staging"

  webgis-watchtower:
    image: containrrr/watchtower
    container_name: webgis-watchtower
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 webgis-frontend webgis-backend --scope webgis.itabirito.staging
    labels:
      - "com.centurylinklabs.watchtower.scope=webgis.itabirito.staging"
