name: Build Frontend 

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Copy data
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Setup Node.js
        uses: actions/setup-node@v2.1.5
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: set env
        run: |
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          echo "NOW=$(date +'%Y.%m.%dT%H.%M.%S')" >> $GITHUB_ENV
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile.frontend
          tags:  |
            paschendale/webgis-itabirito-frontend:stable