name: Build and Publish - Latest

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Copy data
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: set env
        run: |
          echo "VERSION=$(node -p "require('./app/package.json').version")" >> $GITHUB_ENV
          echo "NOW=$(date +'%Y.%m.%dT%H.%M.%S')" >> $GITHUB_ENV
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile.frontend
          tags:  |
            paschendale/webgis-itabirito-frontend:${{ env.VERSION }}
            paschendale/webgis-itabirito-frontend:latest
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile.backend
          tags:  |
            paschendale/webgis-itabirito-backend:${{ env.VERSION }}
            paschendale/webgis-itabirito-backend:latest