name: Version, Build and Publish - Latest

on:
  push:
    branches:
      - 'develop'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Copy data
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Setup Node.js
        uses: actions/setup-node@v2.1.5
      - 
        name: Install dependencies
        run: yarn add semantic-release @semantic-release/git @semantic-release/github
      - 
        name: Semantic Release
        run: npx semantic-release
        env:
          GH_TOKEN : ${{ secrets.GH_TOKEN }}